### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

#getting general info on dataset

len(purchase_data) #780 lines imported
purchase_data.columns # these columns were imported (['Purchase ID', 'SN', 'Age', 'Gender', 'Item ID', 'Item Name', 'Price'], dtype='object')
len(purchase_data.columns) # 7 columns imported
purchase_data.head() #general feel for data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count

* Display the total number of players

In [4]:
totalplayers = purchase_data['SN'].nunique() #each player has unique SN; thus unique SN count should provide unique # of players
summary_TP = pd.DataFrame({"Players": [totalplayers]}) #prep for printing summary
summary_TP

   Players
0      576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [5]:
# extracting datapoints using unique count, mean and count to corresponding results.

nuniqueID = purchase_data['Item ID'].nunique()
priceAVG = purchase_data['Price'].mean()
count = purchase_data['Purchase ID'].count()
rev = purchase_data['Price'].sum()


Gsummary = pd.DataFrame(
    {"Number of Unique Items": [totalplayers], 
     "Average Price": [priceAVG],
     "Number of Purchases": [count],
     "Profit": [rev]})
    
Gsummary

   Number of Unique Items  Average Price  Number of Purchases   Profit
0                     576       3.050987                  780  2379.77

## Gender Demographics
Percentage and Count of Male Players
Percentage and Count of Male Players
Percentage and Count of Female Players
Percentage and Count of Other / Non-Disclosed

In [6]:
# data - filtering gender and SN and dropping duplicates
# datast1 - renaming columns; 
# datast2 - groping by gender, so we'll have total unique count and adding column for percentages

data = purchase_data[['Gender','SN']].drop_duplicates()
data_st1 = data.rename(columns={'SN':'Total Count'})
data_st2 = data_st1.groupby('Gender')['Total Count'].count().reset_index()
data_st2['Percentage'] = 100 * data_st2['Total Count'] / data_st2['Total Count'].sum()
data_st2

                  Gender  Total Count  Percentage
0                 Female           81   14.062500
1                   Male          484   84.027778
2  Other / Non-Disclosed           11    1.909722


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [7]:

#grouping by Gender and calculate sum, count and uniques
pdollar = purchase_data.groupby(['Gender']).sum()
pcount = purchase_data.groupby(['Gender']).count()
unique = purchase_data.groupby(['Gender']).nunique()

#creating dataframe as D
d = pd.DataFrame()

#adding calculations using different calculations.

d['Total Purchase Value'] = pdollar['Price']
d['Purchase Count'] = pcount['Purchase ID']
d['Average Total Purchase Price'] = pdollar['Price'] / pcount['Purchase ID']
d['Average Total Purchase per Person'] = pdollar['Price'] / unique['SN']

d

,Total Purchase Value,Purchase Count,Average Total Purchase Price,Average Total Purchase per Person
Gender,,,,
Female,361.94,113,3.203009,4.468395
Male,1967.64,652,3.017853,4.065372
Other / Non-Disclosed,50.19,15,3.346000,4.562727

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [8]:
purchase_data.describe() # found that minimum is 7 and maximum 45

# Create the bins in which Data will be held
bins = [0, 9, 14, 19, 24, 29, 34, 39, 46]

# Create the names for the four bins
group_names = ["<10", "10-14", "15-19", "20-24", "25-29","30-34","35-39","40+"]

# a - DF with uniques for counting
# countunique - total count for subsequent % calculation
# using pdcut for binning
# groupby to return count by bins
# calculating percentage and adding it to df
# removing SN which help process counting
# printing

a = purchase_data[['Age','SN']].drop_duplicates()
countunique = a['Age'].count()
a["Range"] = pd.cut(a["Age"], bins, labels=group_names)
df_agedem = a.groupby(['Range']).count()
df_agedem['Percentage of Players'] = 100 * df_agedem['Age'] / countunique
del df_agedem['SN']

df_agedem

       Age  Percentage of Players
Range
<10     17               2.951389
10-14   22               3.819444
15-19  107              18.576389
20-24  258              44.791667
25-29   77              13.368056
30-34   52               9.027778
35-39   31               5.381944
40+     12               2.083333

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [26]:
#grouping by Purchase ID to obtain sums and counts
pdollar = purchase_data.groupby(['Purchase ID']).sum()
pcount = purchase_data.groupby(['Purchase ID']).count()

#creating dataframe as Df
df = pd.DataFrame()

# adding columns for price.
df['Total Purchase Value'] = pdollar['Price']
df['Purchase Count'] = pcount['SN']
df['Age'] = purchase_data['Age']

#Bins and groupnames
bins = [0, 9, 14, 19, 24, 29, 34, 39, 46]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29","30-34","35-39","40+"]

#working on data for age range
df["Range"] = pd.cut(df['Age'], bins, labels=group_names)
df_purchase = df.groupby(['Range']).sum()

#working on unique users which is a variable for average purchase per person
x = purchase_data[['Age','SN']].drop_duplicates()
x["Range"] = pd.cut(x["Age"], bins, labels=group_names)
x_a = x.groupby(['Range']).count()

#including calculation columns
df_purchase['Average Total Purchase Price'] =  df_purchase['Total Purchase Value'] / df_purchase['Purchase Count']
df_purchase['People'] = x_a['SN']
df_purchase['Average Total Purchase per Person'] = df_purchase['Total Purchase Value'] / df_purchase['People']
del df_purchase['Age']
del df_purchase['People']

df_purchase

,Total Purchase Value,Purchase Count,Average Total Purchase Price,Average Total Purchase per Person
Range,,,,
<10,77.13,23,3.353478,4.537059
10-14,82.78,28,2.956429,3.762727
15-19,412.89,136,3.035956,3.858785
20-24,1114.06,365,3.052219,4.318062
25-29,293.00,101,2.900990,3.805195
30-34,214.00,73,2.931507,4.115385
35-39,147.67,41,3.601707,4.763548
40+,38.24,13,2.941538,3.186667

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [62]:
y = purchase_data.groupby(['SN']).sum()
y_c = purchase_data.groupby(['SN']).count()


df_top = pd.DataFrame()

df_top['Total Purchase Value'] = y['Price']
df_top['Purchase Count'] = y_c['Item ID']
df_top['Average Purchase Price'] = y['Price'] / y_c['Item ID']

df_topspend = df_top.groupby(['SN']).sum().sort_values(by='Purchase Count', ascending=False)


df_topspend

               Total Purchase Value  Purchase Count  Average Purchase Price
SN
Lisosia93                     18.96               5                3.792000
Iral74                        13.62               4                3.405000
Idastidru52                   15.45               4                3.862500
Asur53                         7.44               3                2.480000
Inguron55                     11.11               3                3.703333
Aina42                         9.22               3                3.073333
Ilarin91                      12.70               3                4.233333
Idai61                         8.23               3                2.743333
Umolrian85                     8.13               3                2.710000
Ialallo29                     11.84               3                3.946667
Tyisur83                       5.36               3                1.786667
Tyidaim51                     11.83               3                3.943333
Pheodaisun84                   8.31               3                2.770000
Hiaral50                       4.19               3                1.396667
Haillyrgue51                   9.50               3                3.166667
Zontibe81                      8.03               3                2.676667
Iri67                         11.37               3                3.790000
Hada39                         8.57               3                2.856667
Raesty92                       8.73               3                2.910000
Rarallo90                      9.05               3                3.016667
Chadolyla44                   11.46               3                3.820000
Saedaiphos46                   8.83               3                2.943333
Saistyphos30                  10.33               3                3.443333
Siallylis44                   10.37               3                3.456667
Chamimla85                     6.30               3                2.100000
Silaera56                      8.48               3                2.826667
Chamjask73                    13.83               3                4.610000
Chanastnya43                   8.82               3                2.940000
Strithenu87                   10.18               3                3.393333
Sondastsda82                   7.89               3                2.630000
...                             ...             ...                     ...
Haerith37                      1.66               1                1.660000
Iduelis31                      1.10               1                1.100000
Hiral75                        1.98               1                1.980000
Idaisuir85                     3.15               1                3.150000
Idacal95                       2.07               1                2.070000
Iathenudil29                   4.60               1                4.600000
Iathem87                       3.19               1                3.190000
Iasursti71                     1.66               1                1.660000
Iasurriacal29                  4.07               1                4.070000
Iarallo65                      1.75               1                1.750000
Iana95                         3.10               1                3.100000
Ialidru40                      3.16               1                3.160000
Iadueria43                     1.71               1                1.710000
Hyaduesu61                     4.23               1                4.230000
Hisridru55                     3.08               1                3.080000
Hilaerin92                     3.61               1                3.610000
Haerithp41                     4.40               1                4.400000
Hiasurria41                    1.61               1                1.610000
Hiarideu73                     2.50               1                2.500000
Heunadil74                     1.54               1                1.540000
Heudai45                       3.47               1                3.470000
Heollyriap59                   3.47               1                3.470000
Heollyra92                     3.07               1                3.070000
Hariphos58                     2.05               1                2.050000
Hallysucal81                   1.66               1                1.660000
Hala31                         1.02               1                1.020000
Haisurra41                     4.40               1                4.400000
Hailaphos89                    3.81               1                3.810000
Haestyphos66                   1.97               1                1.970000
Iskosian40                     3.07               1                3.070000

[576 rows x 3 columns]

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [70]:
p = purchase_data.groupby(['Item Name']).sum()
p_c = purchase_data.groupby(['Item Name']).count()


df_pop = pd.DataFrame()

df_pop['Total Purchase Value'] = p['Price']
df_pop['Purchase Count'] = p_c['Item ID']
df_pop['Average Purchase Price'] = p['Price'] / p_c['Item ID']

df_toppop = df_pop.groupby(['Item Name']).sum().sort_values(by='Purchase Count', ascending=False)


df_toppop

,Total Purchase Value,Purchase Count,Average Purchase Price
Item Name,,,
Final Critic,59.99,13,4.614615
"Oathbreaker, Last Hope of the Breaking Storm",50.76,12,4.230000
Persuasion,28.99,9,3.221111
Nirvana,44.10,9,4.900000
"Extraction, Quickblade Of Trembling Hands",31.77,9,3.530000
Fiery Glass Crusader,41.22,9,4.580000
"Pursuit, Cudgel of Necromancy",8.16,8,1.020000
Brutality Ivory Warmace,19.36,8,2.420000
Singed Scalpel,34.80,8,4.350000
"Shadow Strike, Glory of Ending Hope",25.28,8,3.160000
Retribution Axe,17.76,8,2.220000
"Lightning, Etcher of the King",33.84,8,4.230000
Winter's Bite,30.16,8,3.770000
Wolf,28.32,8,3.540000
Exiled Doomblade,11.41,7,1.630000
Suspension,10.08,7,1.440000
Demise,11.27,7,1.610000
"Oathbreaker, Spellblade of Trials",21.56,7,3.080000
"Heartstriker, Legacy of the Light",12.53,7,1.790000
Malificent Bag,12.25,7,1.750000
"Thorn, Satchel of Dark Souls",9.31,7,1.330000
Vengeance Cleaver,14.35,7,2.050000
"Glimmer, Ender of the Moon",30.80,7,4.400000
Blood Infused Guardian,11.64,6,1.940000
Dawne,6.12,6,1.020000
Agatha,18.48,6,3.080000
"Wolf, Promise of the Moonwalker",26.88,6,4.480000
Amnesia,13.08,6,2.180000
Apocalyptic Battlescythe,11.82,6,1.970000
Ghastly Adamantite Protector,21.48,6,3.580000
...,...,...,...
Curved Axe,2.32,2,1.160000
Stormfury Longsword,9.86,2,4.930000
Foul Titanium Battle Axe,5.84,2,2.920000
"Darkheart, Butcher of the Champion",4.90,2,2.450000
Possessed Core,5.22,2,2.610000
"Rage, Legacy of the Lone Victor",4.96,2,2.480000
"Winterthorn, Defender of Shifting Worlds",4.16,2,2.080000
Whistling Mithril Warblade,2.00,2,1.000000
Spectral Diamond Doomblade,4.08,2,2.040000
Relentless Iron Skewer,5.68,2,2.840000
"Sun Strike, Jaws of Twisted Visions",2.96,2,1.480000
"Heartseeker, Reaver of Souls",7.84,2,3.920000
Foul Edge,7.08,2,3.540000
"Flux, Destroyer of Due Diligence",2.12,2,1.060000
Trickster,3.10,2,1.550000
"Frenzy, Defender of the Harvest",3.96,2,1.980000
Rusty Skull,7.40,2,3.700000
"Torchlight, Bond of Storms",9.30,2,4.650000
Stormfury Mace,9.98,2,4.990000
Unholy Wand,2.24,2,1.120000
Exiled Mithril Longsword,2.00,1,2.000000
Undead Crusader,4.50,1,4.500000
Endbringer,4.66,1,4.660000
"Alpha, Reach of Ending Hope",3.58,1,3.580000
Celeste,4.17,1,4.170000
"Riddle, Tribute of Ended Dreams",3.30,1,3.300000
Betrayer,2.94,1,2.940000
The Decapitator,1.75,1,1.750000
Gladiator's Glaive,1.93,1,1.930000
"Ghost Reaver, Longsword of Magic",2.17,1,2.170000

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [74]:
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60